INSERT INTO SITUACAO VALUES ('ToDo')
INSERT INTO SITUACAO VALUES ('Do')
INSERT INTO SITUACAO VALUES ('Done')

INSERT INTO TAREFA VALUES('4cbb639d-9822-491f-b8e0-6e7112d2b951', '47994848850','Estudar acesso a dados', 'Estudar acesso a dados com dapper no .NET', 1)
INSERT INTO TAREFA VALUES('7043ee78-797f-4a53-8e7a-b34bc1323efc', '47994848850','Estudar angulas','Estudar angular aos fins de semana', 1)